version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  workers:
    build:
      context: ./workers
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgres://postgres:yourpassword@postgres:5432/newspipe
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    command: ./entrypoint.sh

  clock:
    build:
      context: ./workers
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgres://postgres:yourpassword@postgres:5432/newspipe
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    working_dir: /app
    command: bundle exec clockwork config/clock.rb

  backend:
    build:
      context: ./backend
    depends_on:
      - postgres
    ports:
      - "3000:8080"
    environment:
      DATABASE_URL: postgres://postgres:yourpassword@postgres:5432/newspipe

  websocket-server:
    build:
      context: ./websocket-server
    depends_on:
      - redis
    ports:
      - "8080:8080"
    environment:
      REDIS_URL: redis://redis:6379

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: newspipe
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
