version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  scraper-worker:
    build:
      context: ./scrapers
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
    command: bundle exec sidekiq -r ./worker.rb

  scraper-clock:
    build:
      context: ./scrapers
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
    command: bundle exec clockwork clock.rb

  websocket-server:
    build:
      context: ./websocket-server
    depends_on:
      - redis
    ports:
      - "8080:8080"
    environment:
      REDIS_URL: redis://redis:6379

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: newspipe
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=newspipe;Username=postgres;Password=yourpassword
    ports:
      - "5000:80"

volumes:
  pgdata:
