source "https://rubygems.org"

gem "rails", "~> 8.0.2"
gem "pg", "~> 1.1"
gem "sidekiq"
gem "redis"
gem "clockwork"
gem 'ruby-openai'

gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false

group :development, :test do
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end
